name: update

permissions:
  contents: write

on:
  push:
    branches:
      - dev
  workflow_dispatch:

defaults:
  run:
    shell: bash --noprofile --norc -CeEuo pipefail {0}

jobs:
  update:
    if: github.ref == 'refs/heads/dev'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - uses: pnpm/action-setup@v4
        with:
          version: 10
      - name: install
        run: |
          pnpm i

      - name: update base
        run: |
          pnpm run update-base
          ls -l

      - name: update-zip
        run: |
          pnpm run update-zip
          ls -l

      - name: scripts-full.json
        run: |
          curl -L -o scripts-full.json https://raw.githubusercontent.com/mpv-easy/mpsm-scripts/main/scripts-full.json

      - name: commit
        run: |
          rm -rf ./.git
          git config --global init.defaultBranch main
          git init
          git remote add origin https://github.com/ahaoboy/mpv-easy-cdn.git
          git config user.name "MPV_EASY_CDN_UPDATER"
          git config user.email "MPV_EASY_CDN_UPDATER@example.com"
          git add .
          git commit -m "update assets [skip ci]"
          git branch -M main
          git push -f origin main
